os: osx
osx_image: xcode11.1
language: swift
script: xcodebuild clean build test -project Feed/Feed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
script: xcodebuild clean build test -project Feed/Feed.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS" Simulator,OS=12.2,name=iPhone X
